name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  our-pipeline:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.x]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}

      - name: install modules
        run: npm install

      - name: build production project
        run: npm run build

      - name: build storybook
        run: npm run storybook:build

        if: always()
      - name: linting typescript
        run: npm run lint:ts
        continue-on-error: true

      - name: linting styles
        run: npm run lint:css
        continue-on-error: true

      - name: screenshot testing
        run: npm run test:ui:ci
        continue-on-error: true

      - name: unit testing
        run: npm run test:unit
        continue-on-error: true

        if: always()
      - name: ls all
        run: ls -la

      - name: Archive loki diff
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: diff
          path: .loki/difference
