name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  our-pipeline:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}

      - name: install modules
        run: npm install

      - name: build production project
        run: npm run build

      - name: build storybook
        run: npm run storybook:build

      - name: linting typescript
        run: npm run lint:ts

      - name: linting styles
        run: npm run lint:css

      - name: screenshot testing
        run: npm run test:ui:ci

      - name: Preparing visual regression report
        if: failure()
        run: npm run visual:report

      - name: Uploading artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: diff
          path: .loki

      - name: unit testing
        run: npm run test:unit
